import Head from 'next/head'
import { AiFillLinkedin, AiFillGithub, AiOutlineArrowDown, AiOutlineMail } from 'react-icons/ai'
import { BsSunFill, BsMoonStarsFill, BsMessenger, BsFillTabletLandscapeFill } from 'react-icons/bs'
import { BiMenuAltRight } from 'react-icons/bi'
import Image from 'next/image';
import BannerImg from '../public/assets/images/astrocat.png';
import { useState } from 'react';
import { Education } from './components/Education';
import { Skills } from './components/Skills';
import ContactImg  from '../public/assets/images/contact-img.svg'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [tabs, setTabs] = useState('skills');
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Siphamandla Mdletshe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-900 dark:text-white transition-all'>
        <header className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between align-middle'>
            <h1 id="logo" className='text-xl'>
              SSM
            </h1>
            <ul className='flex items-center gap-4'>
              <div className="social-icons flex justify-between gap-4">
                <a href='#' className='text-2xl cursor-pointer'><AiFillLinkedin /></a>
                <a href='#' className='text-2xl cursor-pointer'><AiFillGithub /></a>
              </div>
              <div className="themes">
                {darkMode ? <li onClick={() => setDarkMode(!darkMode)} className='text-2xl cursor-pointer ml-3'><BsSunFill /></li> : <li onClick={() => setDarkMode(!darkMode)} className={'text-2xl cursor-pointer ml-3'}><BsMoonStarsFill /></li>}
              </div>
              <li className='text-2xl cursor-pointer ml-3'><BiMenuAltRight /></li>
            </ul>
          </nav>

          <section id='banner' className='py-10 text-center'>
            <h1 className='text-5xl py-2 font-medium text-rose-600'>Siphamandla Mdletshe</h1>
            <h3 className='text-2xl py-2 text-blue-500'>Software Developer</h3>
            <p className='font-medium py-5 leading-6 text-gray-800 dark:text-gray-400'>
              'bringing things to life with code is my superpower. Happiest when I'm learning, building
              and contributing to meaningful projects. I love building high-quality products
              and bringing them to life through design and code.'
            </p>

            <div className="resume py-4">
              <a href="#" className=' bg-gradient-to-r from-rose-600 to-blue-600 py-2 px-6 text-white rounded-md mt-8'>RESUME </a>
            </div>

            <div className='relative mx-auto bg-gradient-to-b from-yellow-400 rounded-full w-80 h-80 mt-8'>
              <Image src={BannerImg} alt={''} />
            </div>
          </section>
        </header>

        <section id="about" className='py-5'>
          <div className="about-header">
            <h1 className="text-3xl text-center">
              Readme.
            </h1>
            <p className='font-medium py-5 leading-6 text-gray-800 dark:text-gray-400'>
              I am a recent system developer graduate with a passion for software development,
              data science and blockchain. I have a strong foundation in programming concepts
              and am proficient in several programming languages including Java, flutter, and
              Python. I am also familiar with software development methodologies such as Agile
              and Scrum. I am eager to apply my skills and continue learning on the job as an
              entry level software developer. I am a fast learner and I have strong problem-solving
              skills, I also have good verbal and written communication skills. In addition,
              I have completed several projects during my studies that have helped me to
              improve my software development skills. I am an energetic, hardworking, and
              ambitious individual who has developed a mature and responsible approach to
              any task or situation that I am presented with. I excel at collaborating with
              others to achieve a specific goal on time and with excellence. I am always
              eager to learn and share my knowledge. Happiest when I'm learning, building
              and contributing to meaningful projects. I love building high-quality products
              and bringing them to life through design and code.
            </p>
          </div>
          <div className="about-formalities">
            <div className="tabs flex gap-10 pt-5 text-2xl transition-all cursor-pointer">
              <h3 onClick={() => setTabs('skills')} className={tabs === 'skills' ? "border-b-2 border-blue-400 transition-all" : ''}>Skills</h3>
              <h3 onClick={() => setTabs('education')} className={tabs === 'education' ? "border-b-2 border-blue-400 transition-all" : ''} >Education</h3>
            </div>
            <div id="content" className=' py-4'>
              {tabs === 'skills' ? <Skills /> : <Education />}
            </div>
          </div>
        </section>

        <section id="projects" className='py-5'>
          <h1 className="text-3xl text-center">
            Some Things I’ve Built.
          </h1>
          
        </section>

        <section id="contact" className='py-5'>
        <h1 className="text-3xl text-center">
           Let Talk.
          </h1>
          <div>
            <Image src={ContactImg} alt={''} />
          </div>
          <div className="media py-5">
            <ul className='text-xl'>
              <li> < BsMessenger /> mdletshespha38@gmail.com</li>
              <li> <BsFillTabletLandscapeFill /> 0761911814</li>
              <div className="social-icons flex gap-4 justify-center py-2">
                <a href='#' className='text-4xl cursor-pointer'><AiFillLinkedin /></a>
                <a href='#' className='text-4xl cursor-pointer'><AiFillGithub /></a>
              </div>
            </ul>
          </div>
        </section>
      </main>
    </div>
  )
}
